apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pam-cv-brukergenerator"
  namespace: "teampam"
  labels:
    "team": "teampam"
spec:
  image: {{image}}
  liveness:
    path: "/pam-cv-brukergenerator/internal/isAlive"
    port: 9033
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/pam-cv-brukergenerator/internal/isReady"
    port: 9033
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  ingresses: 
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  azure:
    application:
      enabled: true